name: RTx-TabbedUI
module_name: RTx::TabbedUI
version: 0.00_01
abstract: RT TabbedUI Extension
author: Autrijus Tang (autrijus@autrijus.org)
distribution_type: module
build_requires:
  Test::More: 0
private:
  directory:
    - inc
generated_by: Module::Install version 0.24
